### ISSUE TITLE
Error with ADSB Exchange API request

### ISSUE THREAD

**Issue by Tiflo62** [rouyng/airspotbot#23]
Hello,

New problem.
I suscribed to Rapidapi but when I launch the script I got this error:

30-May-22 14:20:43 - airspotbot.adsbget - INFO: Checking for aircraft via ADSBx API (endpoint: rapidapi)
30-May-22 14:20:43 - airspotbot.adsbget - ERROR: Error with ADSB Exchange API request
Traceback (most recent call last):
  File "/home/TEST/airspotbot/airspotbot/adsbget.py", line 244, in check_spots
    response.raise_for_status()
  File "/home/TEST/.local/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://adsbexchange-com1.p.rapidapi.com/json/lat/46.968505/lon/2.489351/dist/250/

Using Test Endpoint on Rapidapi there is no error
![Annotation 2022-05-30 162541](https://user-images.githubusercontent.com/74988027/171012456-8d01d7f3-4ad1-46bd-ab20-a697ec36c9d2.jpg)

Thank you for your help.

**Comment by rouyng** [comment]
I cannot replicate the error you are experiencing. Can you share your asb.config file (with API keys removed)?

**Comment by Tiflo62** [comment]
Here it is:
# airspotbot configuration file
# see README.md for more information

[TWITTER]
# if enable_tweets is set to "n", tweets will be logged but not sent to the twitter api. Useful for testing.
enable_tweets=y
# twitter API key info
consumer_key=xxx
consumer_secret=xxxx
access_token=xxxx
access_token_secret=xxxx
# configure twitter behavior with the following options
# minimum interval between tweets (seconds)
tweet_interval=30
# automatically add descriptions from watchlist.csv in tweets
use_descriptions=n
# tweet when ADSBexchange API is not responding (down or key expired)
# currently nonfunctional, placeholder for planned feature
down_tweet=y
# enable/disable screenshot of globe.adsbexchange.com with each tweet
enable_screenshot=n
# set zoom level of screenshot, choose an integer between 1-20
# The default value of 12 should be fine for most use cases
screenshot_zoom=12


[ADSB]
# aircraft spotting location configuration
# latitude of spot circle center
lat= 46.968505
# longitude of spot circle center
long= 2.489351
# radius of circle to check for spots (in nautical miles)
# must have a value of 1, 5, 10, 25, 100 or 250
radius = 250
# interval to check adsb (seconds)
adsb_interval = 300
# cooldown timer to re-report a previous spot if still active (seconds).
cooldown = 3600
# always spot aircraft with unknown reg number
spot_unknown = n
# always spot aircraft designated as military by ADSBx?
spot_mil = y
# always spot aircraft designated as "interesting" by ADSBx?
spot_interesting = y
# adsbexchange.com API key info
# set adsb_api to "rapidapi" or "adsbx", depending on which endpoint you are using
adsb_api = rapidapi
# if using rapidapi to access ADSBx data, put your api key below.
# if using the ADSBx API directly, enter your feeder uuid below as it acts as your api key
adsb_api_key = xxxxx

[LOCATION]
# options for configuring location description
# location_type should be "manual", "coordinate", "pelias", or "3geonames"
location_type = 3geonames
# description used when "manual" location type is selected
location_description = "near somewhere"
# details of pelias server, used if location_type is "pelias"
pelias_host = http://localhost
pelias_port = 4000
pelias_area_layer = neighbourhood
pelias_point_layer = venue

[MISC]
# set the verbosity of logging messages
# Valid options are as follows, in order from most to least verbose: "debug", "info", "warning", "error", "critical"
# The default value of "info" is usually adequate
logging_level = info

**Comment by rouyng** [comment]
There's nothing wrong with the URL, I can actually make a manual API requests using that URL and it works fine. So, not sure what's going on. Your configuration file looks ok as well. From where did you download the airspotbot files? master branch? v1.0.0 release source code zip? or somewhere else?

**Comment by Tiflo62** [comment]
I cloned the repository and use Python Anywhere to run it. Will investigate on this issue.

**Comment by rouyng** [comment]
Both v1 and v2 are available on RapidAPI, even though v1 is marked deprecated. Yesterday I tested both endpoints manually as well as the current stable v1.0.0 release of airspotbot and could not reproduce your issue. I suspect it is something going on with your python anywhere environment. If you want to pursue this further and can reproduce it on your local machine (or another environment) I'd be happy look into it further. Regardless, v2.0.0 is imminent which will use the v2 endpoint exclusively.
