### ISSUE TITLE
Dockerfile Error

### ISSUE THREAD

**Issue by chevyman142000** [rouyng/airspotbot#29]
Hello - I tried to deploy as a docker container but ran into an issue. See screenshot below of what I'm seeing. Let me know if I can provide any other info. Thanks!

![image](https://user-images.githubusercontent.com/4703038/176725022-6d089125-a927-4b1f-b833-ca82ea58f28c.png)

**Comment by rouyng** [comment]
It looks like you don't have the build context configured correctly. The build context should be set to the airspotbot repo root directory, so it can find all needed files, such as requirements.txt, the config subdirectory and the airsbotbot subdirectory containing the application's python files. 

See [the Docker docs](https://docs.docker.com/engine/reference/commandline/build/) for more info on the different ways to set the build context.

If you are still having trouble, let me know what commands you are using to build/run your docker container.

**Comment by chevyman142000** [comment]
Thanks for getting back to me. This is my first time trying to use a dockerfile, so I'm learning. I appreciate the help and suggestions, will reply back if I run into any further issues or questions. Thanks again!
