### ISSUE TITLE
Won't Install Package on Synology NAS

### ISSUE THREAD

**Issue by zackwilson11** [rouyng/airspotbot#33]
Hello,

I have gotten the airspotbot to pull over but when I go to install the requirements.txt it returns nothing. Whether I'm in an environment or not, it returns the same value... 

(env) zackwilson11@MediaServer:~$ git clone https://github.com/rouyng/airspotbot.git
Cloning into 'airspotbot'...
remote: Enumerating objects: 1114, done.
remote: Counting objects: 100% (69/69), done.
remote: Compressing objects: 100% (53/53), done.
remote: Total 1114 (delta 24), reused 34 (delta 12), pack-reused 1045
Receiving objects: 100% (1114/1114), 599.98 KiB | 3.75 MiB/s, done.
Resolving deltas: 100% (741/741), done.
(env) zackwilson11@MediaServer:~$ pip3 install -r requirements.txt
(env) zackwilson11@MediaServer:~$ pip install -r requirements.txt
(env) zackwilson11@MediaServer:~$ python3 -m pip install -r requirements.txt
(env) zackwilson11@MediaServer:~$

**Comment by rouyng** [comment]
Can you first confirm what version of python you are running with `python3 --version`?
I'm not sure whether the python3 package distributed by Synology are at least 3.10 or newer. That's a hard requirement for running airspotbot. The synology site shows their package is 3.8.6, which would be an issue.
If you can't get 3.10 or newer via the package manager, the best approach is probably to use docker on the NAS and set up airspotbot with the Dockerfile included with this repository. I've done this for several different services running on an older Synology and it works pretty well, although you'd need to learn the basics of docker if you're not already familiar with that.

**Comment by rouyng** [comment]
Also, you don't seem to be in the repository directory when you run your pip command. `cd` into the cloned directory where requirements.txt is located and then try.

**Comment by zackwilson11** [comment]
I think the version is my issue, I have 3.10 installed but it’s only seeing 3.8. So I have to figure out how to truly installed 3.10.. thank you for your time, hope to get this working soon!
