### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by countryboy057** [rouyng/airspotbot#7]
Just checked out the last pelias-geocoder and I am getting this trace error:

16-Aug-20 23:43:21 - INFO: Loading watchlist from watchlist.csv
Traceback (most recent call last):
  File "airspotbot.py", line 134, in <module>
    spots = adsbget.Spotter('asb.config', 'watchlist.csv')
  File "/home/bot/airspotbot/adsbget.py", line 38, in __init__
    self._read_watchlist()
  File "/home/bot/airspotbot/adsbget.py", line 117, in _read_watchlist
    if row[0] == 'Key':
IndexError: list index out of range

**Comment by rouyng** [comment]
can you post the first 3 lines or so of your watchlist.csv? or are you running without a watchlist?

**Comment by countryboy057** [comment]
I have tried mine and then I went with your default offered in the github
repository.

**Comment by rouyng** [comment]
The exception makes me think there is an issue with the first line of the csv file you created. I would check to make sure there's no errant newlines or other things on the first line of your watchlist. Worst case, just replace the entries in the example watchlist with what you need.

**Comment by countryboy057** [comment]
Here are the first 3 lines of my watchlist

Key,Type,Mil Only,Description,Image
H60,TC,N,UH-60 Black Hawk,uh60.jpg
EC45,TC,Y,USAF/US Army/National Guard UH-72 Lakota,uh72.jpg
SW4,TC,Y,USAF RC-26B spy plane,rc26b.jpg

**Comment by countryboy057** [comment]
Ok I found it. If you dont have images you need to delete out the file name....DUH on me

**Comment by rouyng** [comment]
great, glad you were able to find the cause! let me know what you think of the pelias functionality
