### ISSUE TITLE
Trace error

### ISSUE THREAD

**Issue by countryboy057** [rouyng/airspotbot#8]
Using the pelias branch. I wanted to try it out. I am getting this:

-Aug-20 21:21:17 - DEBUG: http://10.100.1.107:4000 "GET /v1/reverse?point.lat=42.799615&point.lon=-78.800013&layers=neighbourhood HTTP/1.1" 200 474
Traceback (most recent call last):
  File "airspotbot.py", line 141, in <module>
    bot.tweet_spot(spot)
  File "airspotbot.py", line 84, in tweet_spot
    location = self.loc.get_location_description(lat, lon)
  File "/home/bot/airspotbot/location.py", line 137, in get_location_description
    geocode = self._reverse_geocode(lat, long)
  File "/home/bot/airspotbot/location.py", line 166, in _reverse_geocode
    area_name = pelias_result.json()["features"][0]["properties"]["name"]
IndexError: list index out of range

**Comment by countryboy057** [comment]
Here is my asb.config location info 

[LOCATION]
# options for configuring location description
location_type = pelias
location_description = "near somewhere"
pelias_host = http://10.100.1.107
pelias_port = 4000
pelias_area_layer = neighbourhood
pelias_point_layer = venue

**Comment by rouyng** [comment]
Try again with most recent commit, my exception handling was bugged when no feature was present on the specified layer

**Comment by countryboy057** [comment]
Working now ! Close issue. Thank You !
